create TABLE IF NOT EXISTS USERS (
    ID INT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    BIRTHDAY DATE,
    CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UNIQUE_LOGIN UNIQUE (LOGIN)
);

create TABLE IF NOT EXISTS FILMS (
    ID INT PRIMARY KEY,
    FILM_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(200),
    RELEASE_DATE DATE,
    DURATION TIME,
    GENRE VARCHAR(50)
);

create TABLE IF NOT EXISTS LIKES (
    FILM_ID INT REFERENCES FILMS (ID),
    USER_ID INT REFERENCES USERS (ID)
);

create TABLE IF NOT EXISTS RATING_MPA (
    FILM_ID INT REFERENCES FILMS (ID),
    RATING_NAME VARCHAR(50)
);

create TABLE IF NOT EXISTS GENRES (
    GENRE_ID INT PRIMARY KEY,
    NAME_GENRE VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS GENRES_FILM (
    FILM_ID INT REFERENCES FILMS (ID),
    GENRE_ID INT REFERENCES GENRES (GENRE_ID)
);

create TABLE IF NOT EXISTS FRIENDS (
    USER_ID INT REFERENCES USERS (ID),
    FRIEND_ID INT REFERENCES USERS (ID),
    STATUS VARCHAR(50)
);
